global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'space-odyssey'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Your FastAPI app on host machine
    metrics_path: '/metrics'